# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mywindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import uic
from PyQt5.QtWidgets import*
from PyQt5.QtCore import*
from PyQt5.QtGui import*


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 550)
        self.backgrounnd = QLabel(Form)
        self.backgrounnd.setGeometry(QRect(-7, 0, 407, 550))
        self.backgrounnd.setText("")
        self.backgrounnd.setPixmap(QPixmap("GUI.png"))
        self.backgrounnd.setScaledContents(False)
        self.backgrounnd.setObjectName("backgrounnd")
        self.light = QLabel(Form)
        self.light.setGeometry(QRect(20, 70, 29, 29))
        self.light.setText("")
        self.light.setObjectName("light")
        self.exit = QPushButton(Form)
        self.exit.setGeometry(QRect(60, 68, 70, 35))
        self.exit.setStyleSheet("background-color: rgba(0,0, 0, 0);")
        self.exit.setText("")
        self.exit.setObjectName("exit")
        self.minimize = QPushButton(Form)
        self.minimize.setGeometry(QRect(340, 10, 51, 31))
        self.minimize.setStyleSheet("background-color: rgba(0,0, 0, 0);")
        self.minimize.setText("")
        self.minimize.setObjectName("minimize")
        self.interfacetext = QTextEdit(Form)
        self.interfacetext.setEnabled(True)
        self.interfacetext.setGeometry(QRect(8, 135, 125, 58))
        self.interfacetext.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.interfacetext.setFrameShape(QFrame.NoFrame)
        self.interfacetext.setObjectName("interfacetext")
        self.reset = QPushButton(Form)
        self.reset.setGeometry(QRect(8, 250, 125, 25))
        self.reset.setStyleSheet("background-color: rgba(0,0, 0, 0);")
        self.reset.setText("")
        self.reset.setObjectName("reset")
        self.checkbox_icmp = QCheckBox(Form)
        self.checkbox_icmp.setGeometry(QRect(30, 460, 61, 20))
        self.checkbox_icmp.setStyleSheet("color: rgba(255, 255, 255, 0);")
        self.checkbox_icmp.setChecked(True)
        self.checkbox_icmp.setObjectName("checkbox_icmp")
        self.checkbox_udp = QCheckBox(Form)
        self.checkbox_udp.setGeometry(QRect(20, 430, 71, 20))
        self.checkbox_udp.setStyleSheet("color: rgba(255, 255, 255, 0);")
        self.checkbox_udp.setChecked(True)
        self.checkbox_udp.setObjectName("checkbox_udp")
        self.checkbox_http = QCheckBox(Form)
        self.checkbox_http.setGeometry(QRect(25, 490, 111, 20))
        self.checkbox_http.setStyleSheet("color: rgba(255, 255, 255, 0);")
        self.checkbox_http.setChecked(True)
        self.checkbox_http.setObjectName("checkbox_http")
        self.checkbox_tcp = QCheckBox(Form)
        self.checkbox_tcp.setGeometry(QRect(20, 400, 71, 20))
        self.checkbox_tcp.setStyleSheet("color: rgba(255, 255, 255, 0);")
        self.checkbox_tcp.setChecked(True)
        self.checkbox_tcp.setObjectName("checkbox_tcp")
        self.checkbox_alarm = QCheckBox(Form)
        self.checkbox_alarm.setGeometry(QRect(25, 320, 101, 20))
        self.checkbox_alarm.setStyleSheet("color: rgba(255, 255, 255, 0);")
        self.checkbox_alarm.setChecked(True)
        self.checkbox_alarm.setObjectName("checkbox_alarm")
        self.checkbox_defender = QCheckBox(Form)
        self.checkbox_defender.setGeometry(QRect(25, 350, 101, 20))
        self.checkbox_defender.setStyleSheet("color: rgba(255, 255, 255, 0);")
        self.checkbox_defender.setChecked(False)
        self.checkbox_defender.setObjectName("checkbox_defender")
        self.icon_icmp = QLabel(Form)
        self.icon_icmp.setGeometry(QRect(10, 460, 40, 20))
        self.icon_icmp.setText("")
        self.icon_icmp.setPixmap(QPixmap("__ON.png"))
        self.icon_icmp.setObjectName("icon_icmp")
        self.icon_udp = QLabel(Form)
        self.icon_udp.setGeometry(QRect(10, 430, 40, 20))
        self.icon_udp.setText("")
        self.icon_udp.setPixmap(QPixmap("__ON.png"))
        self.icon_udp.setObjectName("icon_udp")
        self.icon_http = QLabel(Form)
        self.icon_http.setGeometry(QRect(10, 490, 40, 20))
        self.icon_http.setText("")
        self.icon_http.setPixmap(QPixmap("__ON.png"))
        self.icon_http.setObjectName("icon_http")
        self.icon_tcp = QLabel(Form)
        self.icon_tcp.setGeometry(QRect(10, 400, 40, 20))
        self.icon_tcp.setText("")
        self.icon_tcp.setPixmap(QPixmap("__ON.png"))
        self.icon_tcp.setObjectName("icon_tcp")
        self.icon_alarm = QLabel(Form)
        self.icon_alarm.setGeometry(QRect(10, 320, 40, 20))
        self.icon_alarm.setText("")
        self.icon_alarm.setPixmap(QPixmap("__ON.png"))
        self.icon_alarm.setObjectName("icon_alarm")
        self.icon_defender = QLabel(Form)
        self.icon_defender.setGeometry(QRect(10, 350, 40, 20))
        self.icon_defender.setText("")
        self.icon_defender.setPixmap(QPixmap("__OFF.png"))
        self.icon_defender.setObjectName("icon_defender")
        self.button_alarm = QPushButton(Form)
        self.button_alarm.setGeometry(QRect(10, 320, 40, 20))
        self.button_alarm.setStyleSheet("color: rgba(255, 255, 255, 0);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.button_alarm.setObjectName("button_alarm")
        self.button_defender = QPushButton(Form)
        self.button_defender.setGeometry(QRect(10, 350, 40, 20))
        self.button_defender.setStyleSheet("color: rgba(255, 255, 255, 0);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.button_defender.setObjectName("button_defender")
        self.button_icmp = QPushButton(Form)
        self.button_icmp.setGeometry(QRect(10, 460, 40, 20))
        self.button_icmp.setStyleSheet("color: rgba(255, 255, 255, 0);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.button_icmp.setObjectName("button_icmp")
        self.button_udp = QPushButton(Form)
        self.button_udp.setGeometry(QRect(10, 430, 40, 20))
        self.button_udp.setStyleSheet("color: rgba(255, 255, 255, 0);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.button_udp.setObjectName("button_udp")
        self.button_http = QPushButton(Form)
        self.button_http.setGeometry(QRect(10, 490, 40, 20))
        self.button_http.setStyleSheet("color: rgba(255, 255, 255, 0);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.button_http.setObjectName("button_http")
        self.button_tcp = QPushButton(Form)
        self.button_tcp.setGeometry(QRect(10, 400, 40, 20))
        self.button_tcp.setStyleSheet("color: rgba(255, 255, 255, 0);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.button_tcp.setObjectName("button_tcp")
        self.console = QTextEdit(Form)
        self.console.setGeometry(QRect(140, 69, 250, 211))
        self.console.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 63 8pt;\n"
"color: rgb(255, 255, 255);")
        self.console.setFrameShape(QFrame.NoFrame)
        self.console.setReadOnly(True)
        self.console.setObjectName("console")
        self.status_console = QTextEdit(Form)
        self.status_console.setGeometry(QRect(150, 300, 231, 51))
        self.status_console.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 63 10pt;\n"
"color: rgb(255, 255, 255);")
        self.status_console.setFrameShape(QFrame.NoFrame)
        self.status_console.setReadOnly(True)
        self.status_console.setObjectName("status_console")
        self.traffictext = QTextEdit(Form)
        self.traffictext.setEnabled(True)
        self.traffictext.setGeometry(QRect(8, 215, 125, 25))
        self.traffictext.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.traffictext.setFrameShape(QFrame.NoFrame)
        self.traffictext.setObjectName("traffictext")
        self.apply = QPushButton(Form)
        self.apply.setGeometry(QRect(8, 285, 125, 25))
        self.apply.setStyleSheet("background-color: rgba(0,0, 0, 0);")
        self.apply.setText("")
        self.apply.setObjectName("apply")
        self.traffic_limit = QCheckBox(Form)
        self.traffic_limit.setGeometry(QRect(30, 80, 81, 16))
        self.traffic_limit.setText("")
        self.traffic_limit.setObjectName("traffic_limit")
        self.traffic_box_1 = QLabel(Form)
        self.traffic_box_1.setGeometry(QRect(338, 501, 45, 30))
        self.traffic_box_1.setText("")
        self.traffic_box_1.setObjectName("traffic_box_1")
        self.traffic_box_2 = QLabel(Form)
        self.traffic_box_2.setGeometry(QRect(338, 471, 45, 30))
        self.traffic_box_2.setText("")
        self.traffic_box_2.setObjectName("traffic_box_2")
        self.traffic_box_3 = QLabel(Form)
        self.traffic_box_3.setGeometry(QRect(338, 441, 45, 30))
        self.traffic_box_3.setText("")
        self.traffic_box_3.setObjectName("traffic_box_3")
        self.traffic_box_4 = QLabel(Form)
        self.traffic_box_4.setGeometry(QRect(338, 411, 45, 30))
        self.traffic_box_4.setText("")
        self.traffic_box_4.setObjectName("traffic_box_4")
        self.traffic_box_5 = QLabel(Form)
        self.traffic_box_5.setGeometry(QRect(338, 381, 45, 30))
        self.traffic_box_5.setText("")
        self.traffic_box_5.setObjectName("traffic_box_5")
        self.traffic_limit.raise_()
        self.backgrounnd.raise_()
        self.light.raise_()
        self.exit.raise_()
        self.minimize.raise_()
        self.interfacetext.raise_()
        self.reset.raise_()
        self.checkbox_icmp.raise_()
        self.checkbox_udp.raise_()
        self.checkbox_http.raise_()
        self.checkbox_tcp.raise_()
        self.checkbox_alarm.raise_()
        self.checkbox_defender.raise_()
        self.icon_icmp.raise_()
        self.icon_udp.raise_()
        self.icon_http.raise_()
        self.icon_tcp.raise_()
        self.icon_alarm.raise_()
        self.icon_defender.raise_()
        self.button_alarm.raise_()
        self.button_defender.raise_()
        self.button_icmp.raise_()
        self.button_udp.raise_()
        self.button_http.raise_()
        self.button_tcp.raise_()
        self.console.raise_()
        self.status_console.raise_()
        self.traffictext.raise_()
        self.apply.raise_()
        self.traffic_box_1.raise_()
        self.traffic_box_2.raise_()
        self.traffic_box_3.raise_()
        self.traffic_box_4.raise_()
        self.traffic_box_5.raise_()

        self.retranslateUi(Form)
        QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.interfacetext.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Gulim\';\"><br /></p></body></html>"))
        self.checkbox_icmp.setText(_translate("Form", "CheckBox"))
        self.checkbox_udp.setText(_translate("Form", "CheckBox"))
        self.checkbox_http.setText(_translate("Form", "CheckBox"))
        self.checkbox_tcp.setText(_translate("Form", "CheckBox"))
        self.checkbox_alarm.setText(_translate("Form", "CheckBox"))
        self.checkbox_defender.setText(_translate("Form", "CheckBox"))
        self.button_alarm.setText(_translate("Form", "PushButton"))
        self.button_defender.setText(_translate("Form", "PushButton"))
        self.button_icmp.setText(_translate("Form", "PushButton"))
        self.button_udp.setText(_translate("Form", "PushButton"))
        self.button_http.setText(_translate("Form", "PushButton"))
        self.button_tcp.setText(_translate("Form", "PushButton"))
        self.console.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:8pt; font-weight:56; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Segoe UI Semibold\'; font-size:14pt;\"><br /></p></body></html>"))
        self.status_console.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:10pt; font-weight:56; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Gulim\';\"><br /></p></body></html>"))
        self.traffictext.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Gulim\';\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    Form = QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
